### ISSUE TITLE
Pause the speech

### ISSUE THREAD

**Issue by rishav-karanjit** [nateshmbhat/pyttsx3#152] opened 2020-10-18 08:22 UTC
pyttsx3 has been very helpful. 

But, there is a issue/request. Can you add something like escape sequence to pause the speaking to pyttsx3. For example:
"Hello \100 World" to pause the speaking for 100 seconds between Hello and World.

Current way of pausing speech is not to pass any string to say function but this may not be viable every time.

**Comment by rishav-karanjit** [comment] 2020-10-18 08:23
👍

**Comment by nateshmbhat** [comment] 2020-12-02 12:13
Duplicate of #138

**Closed by nateshmbhat** 2020-12-02 12:13 UTC
Labels: feature_request
